blueprint:
  name: Test blueprint
  domain: automation 
  input:
    trigger_event:
    service_to_call:
trigger:
  platform: event
  event_type: !placeholder trigger_event
action:
  service: !placeholder service_to_call
